### ISSUE TITLE
Hazard Analysis Peer review

### ISSUE THREAD

**Issue by mitcholll** [parishanizam/TeleHealth#113]
Reviewing Team 23

https://github.com/aarnphm/tinymorph/issues/

- [x] https://github.com/aarnphm/tinymorph/issues/123
- [x] https://github.com/aarnphm/tinymorph/issues/124
- [x] https://github.com/aarnphm/tinymorph/issues/125
- [x] https://github.com/aarnphm/tinymorph/issues/126
- [x] https://github.com/aarnphm/tinymorph/issues/127
- [x] https://github.com/aarnphm/tinymorph/issues/128

**Comment by PromishKandel** [comment]
peer review: <Promish Kandel> FMEA components shouldn't have general #124
peer review: Promish Kandel Introduction needs to define what a hazard is #123

**Comment by mitcholll** [comment]
https://github.com/aarnphm/tinymorph/issues/127
https://github.com/aarnphm/tinymorph/issues/128

**Comment by mitcholll** [comment]
Peer Review Complete for Team 23!
