### ISSUE TITLE
Peer Review - Refactor Work Context Model

### ISSUE THREAD

**Issue by nguyes44** [parishanizam/TeleHealth#115]
**Artifact Under Review**
SRS-Volere, 6.2 The Context of the Work

**Team Number for Team Doing the Review**
Team 20

**Description of Issue**
I believe that the diagram under section 6.2 is currently considering too many components. Specifically, I don't think the "Database," "Backend Server," "Language Assessment Website," "Video Analysis Model," and "Audio Analysis Model" should be separate components, but rather one component.

In the Volere [instructions](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/ReferenceMaterial/VolereTemplate16.doc?ref_type=heads) for section 6.2, the example diagram uses the central object "The work of predicting and scheduling the de-icing of roads." From my perspective, I see this section requiring a diagram that answers the question "what does accomplishing this work require (produce) from (to) adjacent systems?" Adjacent systems being "other people, organizations, hardware, and software," which I think the components "Parents and Children" and "Clinicians" satisfy. I believe that these components should be combined into "the work" itself (in whatever way you'd like to define it). 

Also, the connections may need to be reworded to consider input/output, rather than interactions. For example, "Clinicians" can provide something like "Login Info" to the work rather than do the action "Login," and they can receive a "Report" from the work.

This change may require a revamp of sections below 6.2

**Comment by jasminesunhu** [comment]
Feedback has been implemented
