### ISSUE TITLE
Peer Review - Expanding on Constraints 

### ISSUE THREAD

**Issue by arvindshastri** [parishanizam/TeleHealth#117]
**Artifact Under Review**
SRS-Volere, 3. Constraints

**Team Number for Team Doing the Review**
Team 20

**Description of Issue**
- I believe most of your constraints are intuitively defined by the client's needs for the platform, but it would help to add a fit criterion and rationale for each, as defined in the template's Constraints section:

`It is important for each constraint to have a rationale and a fit criterion, as they help to expose false constraints (solutions masquerading as constraints).`

- 3.1.8 is missing a reference to the California law that imposes this constraint.

**Comment by jasminesunhu** [comment]
Feedback has been implemented
