### ISSUE TITLE
Peer Review - Use Case Diagram Issues

### ISSUE THREAD

**Issue by abedmohammed** [parishanizam/TeleHealth#119]
**Artifact Under Review**
SRS, 8.1, Use Case Diagram

**Team Number for Team Doing the Review**
Group 19

**Description of Issue**
The Use Case Diagram (Figure 5) seems too complex and focuses too much on implementation. Use case diagrams should be a high level representation of the interactions between the actors and actions. The use case diagram should not have implementation or internal working details of the application. 

Also, I believe that the extends is being used incorrectly at some points in the diagram. For example, the extends arrow should be reversed for the accept and decline user:
![image](https://github.com/user-attachments/assets/12f0e79e-4641-4ca5-afbb-6adf18112f84)
Here is a video giving more details that is helpful: https://youtu.be/4emxjxonNRI?feature=shared&t=502

Here is an example from 3RA3 in 2023:
![image](https://github.com/user-attachments/assets/161ef041-1438-49ff-8635-71bbc3d40546)

**Sources**
https://www.ibm.com/docs/en/rational-soft-arch/9.6.1?topic=diagrams-use-case
https://www.visual-paradigm.com/guide/uml-unified-modeling-language/what-is-use-case-diagram/

**Comment by mitcholll** [comment]
The Use Case Diagram is at a level of detail and clarity that helped the team figure out the necessary use cases for the system, and how each actor engages with it.

As well, from the diagram I do believe the 'extends' arrows are functioning appropriately. Finalize Order extends to Update Order Status as finalizing an order comes before updating order status. This is similar to how we are using Extends, as Authenticating the user happens prior to Accepting the user.
