### ISSUE TITLE
Peer Review - SRS: Personalization and Internationalization Requirements

### ISSUE THREAD

**Issue by jane-klavir** [parishanizam/TeleHealth#121]
**Artifact Under Review** SRS 11.2: Personalization and Internationalization Requirements

**Team Number for Team Doing the Review** 19

**Description of Issue**
In the rationales of some of the requirements under 11.2, there could be more focus on users. For example, UH-PI1 which states "The system shall support multiple languages" rationalizes this by "The assessment must be conducted in two languages for the purpose of the research study." While this is an important and valid justification, it can also be pointed out that some of the main users;, primary children and their parents, would benefit tremendously from multi-language support.

**Comment by mitcholll** [comment]
Fixed!
