### ISSUE TITLE
Peer Review - Cultural Requirements and Cost Calculation

### ISSUE THREAD

**Issue by aysuozdal** [parishanizam/TeleHealth#122]
**Artifact Under Review**
SRS Section 16.1

**Team Number for Team Doing the Review**
Team 20

**Description of Issue**
- In section 16.1, CU-CR1 has the fit criterion that  mentions that the platform needs to be validated by a cultural "consultant"  and CU-CR2 mentions that the assessments must be fully translated to both languages. However, in Section 23, there is no mention of any costs that are related to "translation" or a "consultant". These sections might be reviewed and the associated cost might be mentioned in the document.

**Comment by jasminesunhu** [comment]
The fit criterion has been revised and feedback has been implemented
