### ISSUE TITLE
Peer Review - SRS: Clearly define user roles and permissions

### ISSUE THREAD

**Issue by jinalkast** [parishanizam/TeleHealth#123]
**Artifact Under Review**
SRS

**Team Number for Team Doing the Review**
Team 19

**Description of Issue**
In section 9.1, authentication is defined by the functional requirements FR-A1 through FR-A5. Although they differentiate between the different types of users, with parent accounts being able to complete assessments and clinician accounts having the permission to view results, there is no requirement discussing how these permissions are enforced, and what happens when edge cases are encountered. Some of the edge cases that can be explored are when parents try to view clinician data or what an admin account's permissions are as a whole (the only data they should be able to view should be encrypted, for privacy reasons). Additionally, you might want to define some rules for error handling in these cases.

**Comment by mitcholll** [comment]
Parents don't have access to the clinician dashboard, which can only be accessed through the clinician's login.
Encryption and security are mentioned further in NFRs as security is a quality of the system, not an authentication functional requirement.
