### ISSUE TITLE
Peer Review - SRS 10.1: Appearance Requirements

### ISSUE THREAD

**Issue by jane-klavir** [parishanizam/TeleHealth#124]
**Artifact Under Review** SRS 10.1: Appearance Requirements

**Team Number for Team Doing the Review**
19

**Description of Issue**
Some of these requirements go into implementation details and are not completely blackbox (e.g. LF-AR3, LF-AR4, LF-ARF).

**Comment by jasminesunhu** [comment]
Feedback has been implemented.
