### ISSUE TITLE
Peer Review - Hazard Analysis: Unclear boundaries & Components

### ISSUE THREAD

**Issue by marmanios** [parishanizam/TeleHealth#131]
**Artifact Under Review**
Hazard Analysis. Section 3

**Team Number for Team Doing the Review**
Group 19

**Description of Issue**
Firstly, the component "User Interface (UI)" isn't really a component. It's more of a part of the actual component which would be the user-facing application. You could also include how it interacts with the backend server.

Secondly, "Assessment Recording" and "Assessment Analysis" are more like features than a component. It seems that maybe you were declaring "Assessment Recording" and "Assessment Analysis" being categories for the modules below them, but they're formatted the same way as the other components so they come off as components themselves. Consider reorganizing the section for clarity.

**Comment by jasminesunhu** [comment]
Feedback has been implemented.
