### ISSUE TITLE
Peer Review - Unreasonable time limit for MFA completion

### ISSUE THREAD

**Issue by jinalkast** [parishanizam/TeleHealth#158]
**Artifact Under Review**
Hazard Analysis, Section 6.1 (HA-SER2)

**Team Number for Team Doing the Review**
Team 19

**Description of Issue**
The fit criterion for HA-SER2 defines that "users accessing sensitive data must pass a multi-factor authentication process within 2 minutes of a code being sent". I understand that the 2 minute limit is for security reasons, but I don't believe it's ample time for all users to be able to complete that task. As society has gotten more comfortable with the notion of MFA, it is definitely possible to enter a code very quickly, especially with aids such as keyboard autofill or copy/paste. However, there may be users with accessibility needs which require them to take more time to finish every step of such a task. My recommendation is to increase the time to something more reasonable (i.e. 5 minutes), which is still low enough to ensure the security of the system.

**Comment by mitcholll** [comment]
Fixed! Accessibility is a primary concern for the group. Thank you for the feedback.
