### ISSUE TITLE
Team Meeting - Oct 28th 2024

### ISSUE THREAD

**Issue by parishanizam** [parishanizam/TeleHealth#160]
**October 28th 2024**

**Attendance**

- [x] Promish Kandel
- [x] Parisha Nizam
- [x] Jasmine Sun-Hu
- [x] Mitchell Weingust

**Agenda

Review VnV report deliverables, understand them, discuss progress and brainstorm questions for TA Meeting 

- Section 3.3 Design Verification Plan - What does this entail, not a lot of information given. What is it, and what do we need to include in documents
- What is Area Testing in Section 4 - is this part of the system or area of the requirement 
- Section 4.1 Do we make tests for every functional requirement or "area" subsection of functional requirements 

- Symbolic Contraints - How do we come up with these without being unnecessary

-  The prof mentioned in class that we dont need to fill in section 5 unit testing, do we need to make that clear/write something in the report

- - What is MIS, when do we complete this?

**Comment by jasminesunhu** [comment]
Assignments
Section 4: whatever functional and non-functional requirements each person wrote they will also do test cases for 
Promish: 9.5,9.6,12
Jasmine: 9.4,10,14,16
Parisha, Mitchell (yall can figure out ur specifics)
Section 9.1-3,11,13,15,17
