### ISSUE TITLE
SRS Peer review

### ISSUE THREAD

**Issue by mitcholll** [parishanizam/TeleHealth#66]
Reviewing Team 23

https://github.com/aarnphm/tinymorph/issues/

- [x] https://github.com/aarnphm/tinymorph/issues/105
- [x] https://github.com/aarnphm/tinymorph/issues/106
- [x] https://github.com/aarnphm/tinymorph/issues/107
- [x] https://github.com/aarnphm/tinymorph/issues/108
- [x] https://github.com/aarnphm/tinymorph/issues/110
- [x] https://github.com/aarnphm/tinymorph/issues/109

**Comment by PromishKandel** [comment]
peer review: <Promish Kandel Team 22> For all of the requirements their is no fit critrion or it isn't apparent #105

**Comment by mitcholll** [comment]
peer review: <Mitchell Weingust Team 22> 8.1 Product Boundary - Use Case Diagram should be expanded on #107 https://github.com/aarnphm/tinymorph/issues/107

peer review: <Mitchell Weingust Team 22> 21 Tasks - Missing critical project planning decisions and deadlines #108 https://github.com/aarnphm/tinymorph/issues/108

**Comment by parishanizam** [comment]
peer review: <Parisha Nizam Team 22> - Missing Traceability Matrix [aarnphm/tinymorph/issues/109](https://github.com/aarnphm/tinymorph/issues/109)

peer review: <Parisha Nizam Team 22> - Missing Formal Specification [aarnphm/tinymorph/issues/110](https://github.com/aarnphm/tinymorph/issues/110)

**Comment by parishanizam** [comment]
Peer Review Complete for Team 23

**Comment by parishanizam** [comment]
Peer Review Complete for Team 23!
